services:
  postgres:
    image: postgres:16-alpine
    container_name: ember-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ember
      POSTGRES_PASSWORD: ember
      POSTGRES_DB: ember_restaurant
    ports:
      - '5434:5432'
    volumes:
      - ember_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ember -d ember_restaurant']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ember-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - ember_redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  ember_postgres_data:
  ember_redis_data:
